### ISSUE TITLE
Updating to Angular 5 and the latest ng-packagr gives library build errors Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Anirudh-Konduri** [dherges/ng-packagr#255] opened 2017-11-07 19:57 UTC
## Type of Issue

```
[*] Bug Report
[ ] Feature Request
```

## Description

I have updated angular to 5.0 (cli - 1.5.0). Angular suggests to update typescript to version '>=2.4.2 & <2.5.0' 

but when i Build my library with "build": "ng-packagr -p ng-package.json", it gives me an error 

**BUILD ERROR Cannot read property 'type' of undefined TypeError: Cannot read property 'type' of undefined** - this is with the node_modules typescript.js file. 

I can get rid of this error by updating typescript to latest i.e, 2.6.1, but then angular gives an build warning 

**build warning -> angular/compiler-cli@5.0.0 requires typescript@'>=2.4.2 <2.5.0' but 2.6.1 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.**

#### How To Reproduce

update ng-packagr to latest version
update angular to 5.0 

Then build your package with "build": "ng-packagr -p ng-package.json"

#### Expected Behaviour

Should be working fine typescript@'>=2.4.2 <2.5.0'

#### Version Information

```
ng-packagr: "^1.5.0"
node: v7.7.2
@angular: v5.0.0
 rxjs: ^5.4.2,
 zone.js: 0.8.14
```

**Comment by dherges** [comment] 2017-11-10 09:30
Hi @Anirudh-Konduri,

can you check and give me feedback whether the issue is resolved with #268 and v1.5.1 of ng-packagr?

The 1.5.1, at least, should fix typescript version incompatibilities. On Angular v5 support in general, there is more...

**Comment by dherges** [comment] 2017-11-10 15:23
If that still failes and the error s down to Angular v5, please can you check whether the issue persists with the [1.6.0-rc.0](https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md#160-rc0-2017-11-10)?

**Comment by Anirudh-Konduri** [comment] 2017-11-10 19:49
Hi @dhergesm 

Thanks for your response. 

I have tried with both the versions. I have typescript v2.4.2

with v1.5.1 i get the same error, 
`BUILD ERROR
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined `

with v1.6.0-rc.0, i get a different error now, 
`BUILD ERROR
ENOENT: no such file or directory, open '/Library/WebServer/istweb/Documents/supporting-apps/istweb-core/src/istweb-core/.ng_pkg_build/@ccs-istweb-core/ts/istweb-core.js'
Error: ENOENT: no such file or directory, open '/Library/WebServer/istweb/Documents/supporting-apps/istweb-core/src/istweb-core/.ng_pkg_build/@ccs-istweb-core/ts/istweb-core.js'`

**Comment by kuhnroyal** [comment] 2017-11-13 15:34
1.6.0-rc0 seems to swallow all errors.

**Comment by minuz** [comment] 2017-11-14 05:50
Hi, I'm running into the same issue and it seems to be some sort of incompatibility with typescript 2.4.2
I tried to upgrade package by package and only updating typescript gives this error straight away.

Hopefully this will give a clue on this matter.

**Comment by minuz** [comment] 2017-11-14 06:51
I found what was wrong on our package.
We had one `import { Observable } from 'rxjs';`
replaced that with 
```
import { Observable } from "rxjs/Observable";
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/mergeMap';
```
My version info:

```
        "versions": {
            "angular": "5.0.1",
            "angularCli": "1.5.0",
            "ngPackagr": "1.6.0-rc.0",
            "coreJs": "2.5.1",
            "zoneJs": "0.8.18",
            "rxJs": "5.5.2",
            "typescript": "2.4.2"
        }
```

And this is working fine.

**Comment by brunano21** [comment] 2018-02-01 14:36
@minuz thank you, I fixed my code as you stated!

**Closed** 2018-02-09 10:42 UTC
Labels: ng@5

**Comment by m-e-conroy** [comment] 2018-02-28 17:52
@minuz Thank you, you saved me untold amounts of time.
