### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by piernik** [dherges/ng-packagr#85] opened 2017-07-31 08:39 UTC
I always get error on compiling:
```
BUILD ERROR
'letProto' is not exported by node_modules\rxjs\operator\let.js
Error: 'letProto' is not exported by node_modules\rxjs\operator\let.js
```

Here is my source code: https://github.com/piernik/alert-error

**Comment by dherges** [comment] 2017-07-31 12:13
Hi @piernik,

I understand your frustation and can reproduce the error w/ your repository.

However, I have never encountered this error in any of the other projects and we have default configurations for the rxjs operators:
 - https://github.com/dherges/ng-packagr/blob/master/lib/steps/rollup.ts#L107
 - https://github.com/dherges/ng-packagr/blob/master/lib/steps/rollup.ts#L228

At first glance, this error is beyond me. Has someone else from the community an idea?

**Comment by isaacplmann** [comment] 2017-07-31 14:10
I get the same error.  I can fix it by adding this to `ng-package.json`:

```json
{
  "lib": {
    "externals": {
      "rxjs/operator/let": "Rx.Observable.let"
    }
  }
}
```

**Comment by piernik** [comment] 2017-07-31 18:34
@dherges I'm not frustrated :) thanks for help.

**Comment by dherges** [comment] 2017-07-31 19:52
@piernik Ok, did @isaacplmann's solution work for you?

If yes, this is a faulty default configuration. Should we fix it?

**Comment by piernik** [comment] 2017-08-01 07:45
@dherges yes it does work!
@isaacplmann thanks

**Comment by piernik** [comment] 2017-08-01 15:19
@dherges  It's not working as it should :/ It compiles but I've got errors when working with compiled version. 'm using the same code from github given earlier.

When I switch to compiled version:
```
import {LukanaAlertyModule} from "../../dist/my-lib";
// import {LukanaAlertyModule} from "../../my-lib/src/lukana-alerty/lukana-alerty.module";
```

```
// import {AlertyService} from "../../my-lib/src/lukana-alerty/alerty.service";
import {AlertyService} from "../../dist/my-lib";
```

throws me `ERROR Error: No provider for NgbAlertConfig!`

**Comment by isaacplmann** [comment] 2017-08-01 15:25
I ran into an error like this as well.  You need to add `"@ng-bootstrap/ng-bootstrap": "_ng_bootstrap"` to the `externals` in your `ng-package.json`.  It will compile fine without that, but you'll end up with two copies of the ng-bootstrap code and the dependency injection won't work because your library will be looking for an `NgbAlertConfig` class that is different from the `NgbAlertConfig` class that the app has registered.

My similar issue was with using `"@angular/material"`, but the solution was the same.  Hope that helps you.  FYI, the problem only manifested when using AoT on the app using the library - if I did `ng serve` with no aot option no errors appeared.

**Comment by dherges** [comment] 2017-08-03 08:06
Can it be fixed by a better default config in ng-packagr?

**Comment by piernik** [comment] 2017-08-03 18:35
@dherges we're asking You :)

**Comment by isaacplmann** [comment] 2017-08-03 18:38
I don't think there's anyway to help people choose what other libraries should be externals, but you could update the rxjs operators default config to include this:

```
      "rxjs/operator/let": "Rx.Observable.prototype"
```

**Comment by dherges** [comment] 2017-08-03 20:25
Like this?

https://github.com/dherges/ng-packagr/pull/89/files

**Comment by isaacplmann** [comment] 2017-08-03 20:26
Yep, that would work for me.

**Comment by dherges** [comment] 2017-08-04 18:56
@piernik If you also confirm, I'll merge the PR!

**Comment by piernik** [comment] 2017-08-07 07:29
It works. You can also make better docs for using external libs like ngBoostrap or material

**Comment by dherges** [comment] 2017-08-07 07:42
@piernik I am lways open to pull requests!

**Closed** 2017-08-07 07:43 UTC
Labels: bug

**Comment by piernik** [comment] 2017-08-09 07:38
@isaacplmann I don't get it. 
With or without 
```
"externals": {
    "@ng-bootstrap/ng-bootstrap": "_ng_bootstrap"
}
```
I always end up with `ng-bootstrap` in `script.es5.js`. And why using underscore in "_ng_bootstrap" ?

**Comment by isaacplmann** [comment] 2017-08-09 13:34
@piernik  You're right - I was assuming that the "_ng_bootstrap" was arbitrary.  However it needs to match the string that "@ng-bootstrap/ng-bootstrap" actually uses to register itself on the global namespace.  I just used the same general format that "@angular/material" uses and assumed it would be fine.  After looking at the [ng-bootstrap source](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/gulpfile.js#L80), I discovered that "ngb" is the string you need to use.  So it should be:

```json
"externals": {
    "@ng-bootstrap/ng-bootstrap": "ngb"
}
```

This works for my lib at least.

**Comment by piernik** [comment] 2017-08-10 08:31
@isaacplmann not for mine:/ still ngBootstrp's code in `es5` file. Can You upload Your example project?

**Comment by dherges** [comment] 2017-08-10 11:40
Can you look whether this is the same cause than #101 ?

**Comment by isaacplmann** [comment] 2017-08-10 13:07
Here's my repo: https://github.com/isaacplmann/ngx-tour - specifically ngx-tour-ng-bootstrap.

**Comment by isaacplmann** [comment] 2017-08-10 13:24
I was sure I had it working before, but when I tried again today the ng-bootstrap was included in the bundle.  However, using the workaround from #101 fixes it.

```json
"externals": {
    "@ng-bootstrap/ng-bootstrap": "ngb",
    "@ng-bootstrap/ng-bootstrap/index": "ngb"
}
```

@piernik, I verified this works on `alert-error` too.  See [this commit](https://github.com/isaacplmann/alert-error/commit/63755e39a89a83c4d561be7371e21526d9863cf0).

**Comment by piernik** [comment] 2017-08-10 13:39
@isaacplmann I just wanted to write You that in Your example is not working either when You wrote Your comment.
You're right - new externals works great!
You don't have to have `"@ng-bootstrap/ng-bootstrap": "ngb",` - works without it.

Now question is why it works that way ?:)

**Comment by piernik** [comment] 2017-08-14 07:26
@isaacplmann @dherges I still can't get it working.
I've made very simple module: https://github.com/piernik/componen-wrapper 
It has no depencies - only angular.

When I import it to my new angular.cli project - only add to app.module:

```
import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';

import {AppComponent} from './app.component';
import {ComponentWrapperModule} from '@lukana/component-wrapper';

@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        ComponentWrapperModule.forRoot()
    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule {
}
```
angular throw error: `Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.`

**Comment by loicsalou** [comment] 2017-11-01 18:10
I had the same issue with primeng's DataTableModule and thanks to this thread I could get it up and running just using following externals in the ng-package.json:

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "primeng/primeng": "primeng"
    }
  }
}
```

However I'm still facing an issue when attempting to package another feature which makes use of @angular/animation. If one creates a file, say "my.animations.ts", in which he declares constant animations like:

```
import {animate, state, style, transition, trigger} from '@angular/animations';

export const swipeAnimation =
  trigger('transition', [
    state('in', style({transform: 'translateX(0)', opacity: '1'})),
    transition('void => *', [
      style({'opacity': '1'}),
      animate('300ms ease-in-out')
    ]),
    transition('* => left', [
      style({transform: 'translateX(-100%)', opacity: '0'}),
      animate('300ms ease-in-out')
    ]),
    transition('* => right', [
      style({transform: 'translateX(100%)', opacity: '0'}),
      animate('300ms ease-in-out')
    ])
  ]);
```
and use it in a component like:

```
@Component({
  selector: 'app-swiper',
  templateUrl: './swiper.component.html',
  styleUrls: ['./swiper.component.scss'],
  animations: [ swipeAnimation ]
})
```

then  ng-packagr crashes at build time.
Workaround is to include animations in the component instead of externalize it in a separate file.

This is a non blocking issue.
I'm really in love with ng-packagr ;-)
