### ISSUE TITLE
Error during the build

### ISSUE THREAD

**Issue by bokzor** [dherges/ng-packagr#81] opened 2017-07-27 09:34 UTC
Hi,
I'm using a the clarity UI framework from vmware.

But the build failed. Do you have any idea where this could be from ?
There is only a index.js into the directory but a .ts seems to be needed during the build.

BUILD ERROR
ENOENT: no such file or directory, open 'C:\my-project\node_modules\clarity-angular\utils\loading\loading.ts'
Error: ENOENT: no such file or directory, open 'C:\my-project\Documents\playground\ihm-tx\node_modules\clarity-angular\utils\loading\loading.ts'

**Comment by dherges** [comment] 2017-07-28 14:00
Can you provide instructions how to exactly reproduce?

**Comment by bokzor** [comment] 2017-07-28 14:18
Here is how : 
I cloned ng-packaged repo.

I add "clarity-angular": "^0.10.0-alpha.5"as peerDependencies into my-lib directory.

Here is tha app.module.ts 

```
@NgModule({
  declarations: [
    AppComponent,
    BasicComponent
  ],
  imports: [
    BrowserModule,
    ClarityModule,
    HttpModule,
    FormsModule,
    ReactiveFormsModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

**Comment by dherges** [comment] 2017-07-28 18:45
And was `clarity-angular` installed into your `node_modules` directory? Did you also add it to `dependencies`?

https://yarnpkg.com/lang/en/docs/dependency-types/#toc-peerdependencies

**Comment by bokzor** [comment] 2017-07-31 06:52
Yes. For sure. The package was added to dependencies in addition to peerDependencies.

**Comment by dherges** [comment] 2017-08-03 20:32
From first sight, I cannot see why this error happens. It looks strange that it's trying tor esolve to some `.ts` source files. It should not do that. For compile-time validation of a `peerDependency`, it should use only the `.d.ts` type definition files but must not need to include any javascript (or whatsoever code) in a lib (this only happens when the mpdule bundlers like webpack produce the assets for the final app).

**Comment by dherges** [comment] 2017-08-11 08:16
Closing this issue since no updates.

If the issue persists, feel free to comment and re-open.

**Closed by dherges** 2017-08-11 08:16 UTC
Labels: question

**Comment by bokzor** [comment] 2017-09-12 14:51
I have some news.
The steps to reproduce :
Create a module as follows :

**Comment by bokzor** [comment] 2017-09-12 14:58
I have some news :
Steps to reproduce : 

Create a module as follows 
```

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SelectComponent } from './select.component';
import { ClarityModule } from 'clarity-angular';

@NgModule({
  imports: [
    CommonModule,
    ClarityModule
  ],
  declarations: [
    SelectComponent
  ],
  exports: [SelectComponent]
})
export class SelectModule { }

```
Add 
`      <clr-icon shape="caret down"></clr-icon>
`
in a component.

The problem comes from sorcery.js.
I have to do an early return as follows :   return Promise.resolve()
I'm able to compile my project successfully.

**Comment by justindsmith** [comment] 2017-10-05 00:50
I've run into this issue as well. I've forked the `ng-packaged` repo to provide a reproducible environment: https://github.com/justindsmith/ng-packaged-clarity

You can see the commit I added for the only changes: https://github.com/justindsmith/ng-packaged-clarity/commit/238d76b4e968ca700f31edae67cea8cf4554747f

I'm seeing the following output:
```
$ yarn build:lib
yarn build:lib v1.0.2
$ ng-packagr
Building Angular library from /Users/jsmith/Projects/ng-packaged/ng-package.json

BUILD ERROR
ENOENT: no such file or directory, open '/Users/jsmith/Projects/ng-packaged/node_modules/clarity-angular/icon/index.ts'
Error: ENOENT: no such file or directory, open '/Users/jsmith/Projects/ng-packaged/node_modules/clarity-angular/icon/index.ts'

error Command failed with exit code 111.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any ideas on what might be causing it? Is this an issue in how clarity is packaging their libraries / modules?

**Comment by dherges** [comment] 2017-10-08 18:02
Hi @bokzor @justindsmith,

can you check #129 and special the `lib.externals` configuration?
