### ISSUE TITLE
"Cannot create property 'modifierFlagsCache'" when using string-based enums

### ISSUE THREAD

**Issue by luchsamapparat** [dherges/ng-packagr#206] opened 2017-10-22 13:29 UTC
First of all: I'm not sure if this is an issue with `ng-packagr` or maybe `tsickle` or even `typescript` itself. However, I didn't know how to reproduce this issue without `ng-packagr`, so I thought it would be best to start here. Feel free to point me in the right direction.

## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Whenever I use a [string-based enum](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) (available since TypeScript 2.4) in my project, the build process fails with this error message:

```
> ng-packagr -p ng-package.json

Building Angular library
Generating bundle for mfc-issue

BUILD ERROR
Cannot create property 'modifierFlagsCache' on string 'some string'
TypeError: Cannot create property 'modifierFlagsCache' on string 'some string'
    at Object.getModifierFlags (C:\Users\mal\Projekte\mfc-issue\node_modules\typescript\lib\typescript.js:9685:33)
    at Object.getCombinedModifierFlags (C:\Users\mal\Projekte\mfc-issue\node_modules\typescript\lib\typescript.js:10388:24)
    at hasModifierFlag (C:\Users\mal\Projekte\mfc-issue\node_modules\tsickle\build\src\tsickle.js:72:16)
    at Annotator.maybeProcess (C:\Users\mal\Projekte\mfc-issue\node_modules\tsickle\build\src\tsickle.js:538:13)
    at Annotator.Rewriter.visit (C:\Users\mal\Projekte\mfc-issue\node_modules\tsickle\build\src\rewriter.js:52:19)
    at Annotator.maybeProcessEnum (C:\Users\mal\Projekte\mfc-issue\node_modules\tsickle\build\src\tsickle.js:1188:22)
    at Annotator.maybeProcess (C:\Users\mal\Projekte\mfc-issue\node_modules\tsickle\build\src\tsickle.js:676:29)
    at Annotator.Rewriter.visit (C:\Users\mal\Projekte\mfc-issue\node_modules\tsickle\build\src\rewriter.js:52:19)
    at C:\Users\mal\Projekte\mfc-issue\node_modules\tsickle\build\src\rewriter.js:84:19
    at visitNodes (C:\Users\mal\Projekte\mfc-issue\node_modules\typescript\lib\typescript.js:11911:30)
```

#### How To Reproduce

Put a string-based enum in your project:

```ts
export enum MyEnum {
    StrVal = 'some string'
}
```

I created a simple project with for reproduction:
https://github.com/luchsamapparat/mfc-issue

#### Expected Behaviour

no error :)

#### Version Information

```
ng-packagr: v1.5.0-rc.0
node: v8.0.0
typescript: 2.5.3
@angular: n/a
rxjs: n/a
zone.js: n/a
```

**Comment by DavidParks8** [comment] 2017-10-22 16:32
I'm doing some debugging, and I've ruled out typescript, as it compiles if you run tsc. I'll update here as I find out more.

**Comment by DavidParks8** [comment] 2017-10-22 16:48
If you're on windows, you can set the build command in package.json to be `"build": "SET DEBUG=true && ng-packagr -p ng-package.json",` and you will see what ng-packagr is actually doing. Doing so reveals to me that the failure comes directly from the `main` function from `@angular/tsc-wrapped`. I'm afraid there's nothing the ng-packagr team can do since this is a limitation of the angular compiler (ngc). I do recall that they don't yet officially support typescript >=2.4. Also, based upon the stack trace, it looks like tsickle is failing inside ngc.

**Comment by DavidParks8** [comment] 2017-10-22 16:59
We might want to keep an eye on https://github.com/angular/tsickle/pull/627

**Comment by ghiscoding** [comment] 2017-10-23 19:43
I have the same problem and it's worth to know that setting strings on `Enum` are available only since TypeScript version `2.4` and `ng-packagr` is set to `~2.3.3` in `package.json`. However, updating TypeScript to latest still throws the error. 

After some googling, there seem to be 2 options available to bypass this issue (as shown in this [SO](https://stackoverflow.com/a/17839554/1212166) question). 
1- Change `enum` to a `class` and add `static` in front of each `enum` property
```javascript
export class Order { 
  static Asc = 'Asc'; 
  static Desc = 'Desc' 
}
```
2- Use `enum` as usual but simply add `<any>` in front of each `enum` property
```javascript
export enum Order { 
  Asc = <any>'Asc', 
  Desc = <any>'Desc' 
}
```
I decided to use the 2nd option since it remains as an Enum, even though it's a little bit hacky. This is still a hack, so if someone finds the correct way to fix it, then please advise.

**Comment by dherges** [comment] 2017-10-23 19:46
Thanks for the typescript version explanation. This is due to ngc, the angular compiler. In angular 4.4.x it is recommended to use typescript 2.3.x afaik

Cheers, David

**Comment by dherges** [comment] 2017-11-13 16:41
Hi all,

can you check whether 1.5.1 solves the issue as from this version on, ng-packagr uses the user installed typescript in the project repository?

**Comment by luchsamapparat** [comment] 2017-11-14 15:37
We haven't updated to Angular 5 yet. Are the packages created with 1.5.1 compatible with Angular 4.x?

**Comment by ghiscoding** [comment] 2017-11-14 15:58
That's a good point, it looks like the `package.json` is now showing `"@angular/core": "~5.0.0"` and I also haven't moved to Angular `5.x` yet.

**Comment by denver-HJS** [comment] 2017-11-17 20:07
Oddly enough I haven't ran into this problem myself, but a colleague of mine did while using version 1.5.1

My versions that work:
```
C:\src\git\web-wrapper>ng version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.5
node: 7.2.1
os: win32 x64
@angular/animations: 4.4.4
@angular/cdk: 2.0.0-beta.12-7fe1b81
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.5.3

yarn list ng-packagr
yarn list v0.27.5
└─ ng-packagr@1.4.0
Done in 4.45s.
```

He is using:
```
@angular/cli: 1.5.2
...all deps associated with fresh v1.5.2 install
ng-packagr: 1.5.1
typescript: 2.6.1
```

**Comment by dherges** [comment] 2017-11-17 20:39
Please check your typescript versions!

There are issues with certain versions of Angular and TypeScript. Current reco is Angular v4: tsc@2.3.x. Angular v5: tsc@2.4.x

https://github.com/angular/angular-cli/blob/ae53cb1319a2ef3b687cc0eeabb371ff5c048af0/packages/%40angular/cli/upgrade/version.ts#L170-L172

Starting from ng-packagr@1.5.1, the typescript version from your project is used, as ng-packagr now depends on a `peerDependencies: { typescript: "~2.3.x" }` for Angular v4. For Angular v5, in the 2.0.0-rc.0, it's `peerDependencies: { typescript: "~2.4.x" }`

**Comment by denver-HJS** [comment] 2017-11-17 21:26
@dherges - I think we can rule out Angular CLI's _ngc_ and any related Angular recommendations though, because my colleague's project I mentioned is pure TypeScript and doesn't actually use Angular. He only added it as a test to see if it'd fix the issue.

However, doing the type casting workaround that @ghiscoding mentioned does get past the error. I guess I only made my comment, because it's curious to me that I can use _ng-packagr_ v1.4.0 in combination with _Typescript_ v2.5.3 and not run into the same problem.

**Comment by denver-HJS** [comment] 2017-11-17 21:40
@dherges - correct, sorry, I didn't fully think through what @DavidParks8 was saying when he pointed out that the failure occurs with the Angular CLI's _ngc_

I'm not sure what the project's preferred way for proposing enhancements is, but hopefully given the context of the thread this is okay. My colleague's project happens to be a pure TypeScript implementation with no Angular involved. The package is intended to be consumed by Angular projects, but it wouldn't necessarily have to be (if that makes sense). 

Would it be a large/worthwhile effort to add a configuration option that skips running the source through the Angular compiler? It seems like that could open this project up to a wider user base (which I suppose widening the scope may or may not be desired)

**Comment by dherges** [comment] 2017-11-17 22:05
@denver-HJS Sure, it's good!

Here's a draw-up of the transformation pipeline that is happening:

![docs/transformation-pipeline.jpg](https://github.com/dherges/ng-packagr/blob/master/docs/transformation-pipeline.jpg?raw=true)


What you're describing ... you'd like to have just `tsc` as the very first step (no styles, no templates, no AoT metadata). So you go from `*.ts` sources to es2015 (`*.d.ts` + `*.js` / target: es2015 / module: es2015) and then run through the remainer of the rollup / tsc / uglify transformations?

**Comment by denver-HJS** [comment] 2017-11-17 22:23
@dherges thanks for including the informative draw-up. Yes, that's exactly what I'm proposing!

**Comment by skorunka** [comment] 2017-11-21 12:59
Got a same problem `Cannot create property 'modifierFlagsCache' on string 'levelZ'` where my enum is:
```
export enum ProductsHierarchyFilter {
	levelZ = 'levelZ',
...
```

@ghiscoding solution no. 2 does not work for me: 
![image](https://user-images.githubusercontent.com/218913/33073706-a81fcb3a-cebb-11e7-8c7f-3a3d18a18029.png)

```
	"peerDependencies": {
		"@angular/animations": "5.0.2",
		"@angular/common": "5.0.2",
		"@angular/compiler": "5.0.2",
		"@angular/core": "5.0.2",
		"@angular/forms": "5.0.2",
		"@angular/http": "5.0.2",
		"@angular/platform-browser": "5.0.2",
		"@angular/platform-browser-dynamic": "5.0.2",
		"@angular/router": "5.0.2",
		"@progress/kendo-angular-buttons": "2.0.0",
		"@progress/kendo-angular-dateinputs": "1.4.0",
		"@progress/kendo-angular-dropdowns": "1.2.4",
		"@progress/kendo-angular-excel-export": "1.0.5",
		"@progress/kendo-angular-grid": "1.6.1",
		"@progress/kendo-angular-inputs": "1.3.3",
		"@progress/kendo-angular-intl": "1.3.0",
		"@progress/kendo-angular-l10n": "1.0.5",
		"@progress/kendo-data-query": "1.1.1",
		"@progress/kendo-drawing": "1.4.0",
		"@progress/kendo-theme-default": "2.45.0",
		"core-js": "2.5.1",
		"rxjs": "5.5.2",
		"zone.js": "0.8.18"
	},
	"devDependencies": {
		"@angular/cli": "1.5.3",
		"@angular/compiler-cli": "5.0.2",
		"@angular/language-service": "5.0.2",
		"@types/jasmine": "2.8.2",
		"@types/node": "8.0.53",
		"codelyzer": "4.0.1",
		"jasmine-core": "2.8.0",
		"jasmine-spec-reporter": "4.2.1",
		"karma": "1.7.1",
		"karma-chrome-launcher": "2.2.0",
		"karma-cli": "1.0.1",
		"karma-coverage-istanbul-reporter": "1.3.0",
		"karma-jasmine": "1.1.0",
		"karma-jasmine-html-reporter": "0.2.2",
		"ng-packagr": "1.6.0",
		"protractor": "5.2.0",
		"ts-node": "3.3.0",
		"tslint": "5.8.0",
		"typescript": "2.6.1"
	}
```

You think it might be problem with the typescript version I'm using?

**Comment by ghiscoding** [comment] 2017-11-21 13:31
@skorunka I also have the allow synthetic option enable in my `tsconfig.json`

```javascript
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    ...
```

Not sure if that is the reason it works for me, I use that option for other reasons (mainly for `moment.js` import). But who knows it might be the reason, give it a try

**Comment by skorunka** [comment] 2017-11-21 14:12
@ghiscoding It did not help, still get this `Computed values are not permitted in an enum with string valued members.`. The static class helped. Thanks.

**Comment by ghiscoding** [comment] 2017-11-24 16:32
@skorunka have you also added the `"allowSyntheticDefaultImports": true` in your `tsconfig`? it is required if you want to the casting `<any>`

@dherges I updated my library to `Angular 5` and updated `ng-packagr` to `1.6.0` and I still see the error unfortunately. 

See below for some of my settings and code to test with

package.json
```javascript
"devDependencies": {
    "@angular/core": "^5.0.0",
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@angular/cli": "1.5.4",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "ng-packagr": "^1.6.0",
    "typescript": "~2.4.2",
    ...
```

Export Enum 
```javascript
export enum SortDirection {
  ASC = 'ASC',
  DESC = 'DESC'
}
```
I still get the following error
```bash
Cannot create property 'modifierFlagsCache' on string 'ASC'
TypeError: Cannot create property 'modifierFlagsCache' on string 'ASC'
...
```
If I put back the monkey patch, casting to `<any>` with `tsconfig` of `allowSyntheticDefaultImports: true`, it works without errors.
```javascript
export enum SortDirection {
  ASC = <any>'ASC',
  DESC = <any>'DESC'
}
```

I don't mind sticking to the monkey patch, it's not exactly terrible and it's still an Enum. I'm just providing you feedback here. Thanks for your awesome packager :)

**Comment by dherges** [comment] 2017-11-25 13:28
For Angular 5, please use the 2.0.0 release candidates. make sure you have a typescript version that is recommended / support by angular. It is "~2.4.x" for Angular 5. See the changelog for details.

**Comment by skorunka** [comment] 2018-01-17 11:37
@dherges Hi, I can confirm the enums works with `"ng-packagr": "^2.0.0-rc.11"` good job. Thank you.

**Comment by skorunka** [comment] 2018-01-17 11:40
@dherges Is there a new format how to define the `exetnals`?
With v2 I got his warnings:
```
Bundling to UMD
No name was provided for external module '@progress/kendo-angular-grid' in options.globals – guessing 'kendoAngularGrid'
No name was provided for external module '@progress/kendo-angular-dropdowns' in options.globals – guessing 'kendoAngularDropdowns'
No name was provided for external module '@progress/kendo-angular-buttons' in options.globals – guessing 'kendoAngularButtons'
No name was provided for external module '@progress/kendo-data-query' in options.globals – guessing 'kendoDataQuery'
```

```json
{
	"$schema": "../node_modules/ng-packagr/ng-package.schema.json",
	"dest": "../dist/my-lib",
	"lib": {
		"entryFile": "src/public_api.ts",
		"externals": {
			"@progress/kendo-angular-buttons": "@progress/kendo-angular-buttons",
			"@progress/kendo-angular-dateinputs": "@progress/kendo-angular-dateinputs",
			"@progress/kendo-angular-dropdowns": "@progress/kendo-angular-dropdowns",
			"@progress/kendo-angular-excel-export": "@progress/kendo-angular-excel-export",
			"@progress/kendo-angular-grid": "@progress/kendo-angular-grid",
			"@progress/kendo-angular-inputs": "@progress/kendo-angular-inputs",
			"@progress/kendo-angular-intl": "@progress/kendo-angular-intl",
			"@progress/kendo-angular-l10n": "@progress/kendo-angular-l10n",
			"@progress/kendo-data-query": "@progress/kendo-data-query",
			"@progress/kendo-drawing": "@progress/kendo-drawing"
		}
	}
}
```

**Comment by pfeigl** [comment] 2018-01-25 17:46
@skorunka : See https://github.com/dherges/ng-packagr/pull/395

**Comment by dherges** [comment] 2018-02-21 18:36
Closing this issue as v2 now supports typescript 2.5+ an onwards.

**Closed by dherges** 2018-02-21 18:36 UTC
Labels: community: need feedback
