### ISSUE TITLE
exclude folder with demo application

### ISSUE THREAD

**Issue by Arikael** [dherges/ng-packagr#313] opened 2017-11-24 11:12 UTC
## Type of Issue
```
[ ] Bug Report
[ ] Feature Request
[ x ] Question
```

## Description

I know this issue came up before in one or the other form, but let me explain.

I have an angular library which I compile with ng-packagr (thanks for that, it made the whole process so much easier :) ). Because I need to test AoT before publishing the library I created a folder called "demo" which contains a whole, albeit simple, angular app including own package.json and node_modules folder.

This breaks the building process because of the following issue(s).
- https://github.com/dherges/ng-packagr/issues/141
- https://github.com/dherges/ng-packagr/issues/51

If I don't have the demo folder everything works fine, I assume because ng-packagr includes everything below the src-directory.

Would it be possible to add a feature to completly (html, js, ts, css etc.) ignore a certain folder or to specifically include only certain folders?

#### Version Information

```
ng-packagr: v2.0.0
node: v8.0.53
@angular: v5.0.3
```

**Comment by Eufix** [comment] 2017-11-24 14:10
This feature is already implemented.
ng-packagr will only package files reachable from entry file specified in 'ng-package.json'
(usualy public_api.ts)

I have created demo project that has library project (ng2-lib) that containes testbed application:
https://github.com/Eufix/ng2-school

Take a look how it is configured:
package.json (script:  "packagr": "ng-packagr -p src/app/modules/ng-package.json")
src/app/modules/ng-package.json
src/app/modules/public_api.ts

hope this helps.

**Comment by Arikael** [comment] 2017-11-24 14:29
What exactly means "reachable from entry file..."?
Does it mean it only includes files which are included/required or will process everything in the folder and subfolder?

if the folder structure is as following

- demo
  - app (with node_modules etc.)
- src
  - public_api.ts
- ng-package.json

ng-packagr will display errors that point to the demo folder.

**Comment by Eufix** [comment] 2017-11-24 14:38
Only files included from public_api.ts.

**Comment by Arikael** [comment] 2017-11-25 08:58
I'll have a look at it after the weekend.
If I'm not mistaken, ng-packagr respectively one of its libraries (gulp template inliner) seems to pick up files from the /demo folder (see last of my comment).

But I will be able to provide more information next week.

**Comment by Arikael** [comment] 2017-11-28 14:03
If you use the folder structure as following
- demo
  - app (with node_modules etc.)
- src
   - public_api.ts
- package.json (incuding ng-packagr config)

I get the following error
`Error: ENOENT: no such file or directory, open 'C:\Users\haehadmin\Documents\Visual Studio 2017\Projects\zhaw-angular\demo\node_modules\@angular\animations\src\my-component-tpl.html'
`
this is because `gulp-inline-ng2-template` tries to parse a comment as template (see https://github.com/dherges/ng-packagr/issues/141) 

and it seems `gulp-inline-ng2-template` just picks up everything (even from node_modules) below `src` and tries to inline it which of course fails.

If I move everything under `src` into a subfolder `lib` (lib/src) and add a package.json everything works.

I assume this is is not a ng-packagr problem but a `gulp-inline-ng2-template` problem.

**Comment by dherges** [comment] 2017-11-29 10:57
Hi @Arikael @Eufix,

I am not sure if this is a question or a duplicate of existing issues. There are also several demo repositories and blog posts doing this:


https://medium.com/@ngl817/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e

https://github.com/dherges/ng-packaged

https://github.com/dherges/nx-packaged

**Closed by dherges** 2017-11-29 10:57 UTC
Labels: duplicate, question

**Comment by brunano21** [comment] 2018-02-01 15:41
@dherges @Arikael I'm facing the same issue. Do you guys have any hint for that? It's like ng-packagr builds whatever `demo` folder contains.

**Comment by Arikael** [comment] 2018-02-26 08:22
I gave up and created a demo and a lib folder.
The problem is, as mentioned above, `gulp-inline-ng2-template`
