### ISSUE TITLE
Injection (Component, Token) fails during building (3.0.0-rc.3, also ^2.0.0) in Angular 6.0

### ISSUE THREAD

**Issue by georgiee** [dherges/ng-packagr#852] opened 2018-05-08 16:26 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
While upgrading my UI library to Angular 6 I encountered a problem with Injection during the build with ng-packagr (Error Message in appended and inside the minimal example)

Here is the most minimal example I was able to create.
https://github.com/georgiee/ng-packagr-inject
(I tried to use stackblitz so you can quickly take a look- but it's just not made for CLI stuff)

The weird thing is: Injection of the Token and the Component Reference happens in two different places. But once I remove either of them the problem goes away.

I can imagine that this is a ngc problem as it fails during the step `Compiling TypeScript sources through ngc` inside the file `ng-packagr/lib/ngc/compile-source-files.js` but I'm unsure so that I rather open this issue.

I don't know if this is related:
https://github.com/angular/angular/issues/23734
A quick `@Injectable({providedIn: 'root'})` did not help in my example.

#### How To Reproduce
Just build the library in the example project. I also wanted to try a raw ngc example but I have no real clue where to begin. I want to drop this issue here instead in case you see what's going on.

#### Expected Behaviour
The build should be fine in this easy scenario.

#### Version Information

```
ng-packagr:            3.0.0-rc.3
@angular/compiler:     6.0.0
rollup:                0.58.2
tsickle:               0.27.5
typescript:            2.7.2
```

Here the error details:

> Warning: Can't resolve all parameters for FooClass in ng-packagr-bug-inject/projects/library/foo/public-api.ts: (?). This will become an error in Angular v6.x

```
BUILD ERROR
projects/dist/library/bar/public-api.d.ts(1,31): error TS2307: Cannot find module '@my/library/some-component'.
: Can't resolve all parameters for BarDirective inng-packagr-bug-inject/projects/dist/library/bar/my-library-bar.d.ts: (?).

Error: projects/dist/library/bar/public-api.d.ts(1,31): error TS2307: Cannot find module '@my/library/some-component'.
: Can't resolve all parameters for BarDirective in ng-packagr-bug-inject/projects/dist/library/bar/my-library-bar.d.ts: (?).

    at Object.<anonymous> (ng-packagr-bug-inject/node_modules/ng-packagr/lib/ngc/compile-source-files.js:62:68)
    at Generator.next (<anonymous>)
    atng-packagr-bug-inject/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (ng-packagr-bug-inject/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (ng-packagr-bug-inject/node_modules/ng-packagr/lib/ngc/compile-source-files.js:21:12)
    at Object.<anonymous> (ng-packagr-bug-inject/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:42:34)
    at Generator.next (<anonymous>)
    atng-packagr-bug-inject/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

**Comment by georgiee** [comment] 2018-05-09 13:57
Here my follow-up. Seems to be related to ng-packagr as it's failing with rc3 in both Angualr 5 and Angular 6 environments.

I created commits for three different combinations and commited the generated files too. Hope that helps. 

https://github.com/georgiee/ng-packagr-rc3-inject-bug

**Comment by alan-agius4** [comment] 2018-05-12 07:35
I had a quick look at this, at it looks like the issue is related to paths. As in your case you have a sort of 3 level dependency

`foo` depends on `bar` and `bar` depends on `some-component`.

There are two issue here;
1) In https://github.com/dherges/ng-packagr/blob/master/src/lib/ngc/transform-source-files.ts (No paths sets)
2) https://github.com/dherges/ng-packagr/blob/master/src/lib/ng-v5/entry-point/ts/compile-ngc.transform.ts#L22 (Only direct dependencies are added)

I try to find some time to solve this issue in the coming days

**Comment by georgiee** [comment] 2018-05-14 10:27
Hi Alan,
thanks for your answer. Did you also take notice of the example in the other issue https://github.com/dherges/ng-packagr/issues/854 where I noted a different error bound to injection (`isSkipSelf`). It's unfortunate that I combined it that way instead of creating a new issue but I didn't want to create too much noise until I tested it against my library.

I will build the latest master of ng-packagr and give it another try today to look what errors are haunting me then. Thanks for pointing out the locations with issues. This helps building up a mental image of what ng-packagr is doing and maybe I can find a solution with this.

**Comment by alan-agius4** [comment] 2018-05-15 05:36
I should be able to commit a fix for this issue soon

**Comment by abbazabacto** [comment] 2018-05-22 18:43
Wanted to file a bug about this until I came across this. Already made a small repo where the same issue is demonstrated, will drop it here anyway: https://github.com/abbazabacto/ngpackagr-issue

@alan-agius4 I build your branch `feature/fix-issue-852` locally and the issues disappears like snow for the sun. Any idea when a new RC will be released with this patch?

FYI In my real (private) package the original compiler warning was swallowed away by the following error
```
BUILD ERROR
Cannot read property 'isSkipSelf' of null
TypeError: Cannot read property 'isSkipSelf' of null
```
Made it very hard to find the origin, had to just remove dependencies to see which one caused the issue.

**Comment by alan-agius4** [comment] 2018-05-22 18:54
//cc @dherges to see when this can get merged

**Closed** 2018-05-25 17:01 UTC
