### ISSUE TITLE
Import path of third-party library is rewritten from `openlayers` to `openlayers/index`

### ISSUE THREAD

**Issue by adjioev** [dherges/ng-packagr#118] opened 2017-09-06 06:09 UTC
## Type of Issue

- [ ] Bug Report
- [x] Feature Request

## Description

I have a module MapModule that is using openlayers 3 library, so in map.component.ts I have 
`import * as ol from 'openlayers';`

When I run packagr, rollup compiles files with the following line:
`import { Map, View, control, format, layer, proj, source } from 'openlayers/index';`

i.e. it adds `/index` at the end, when it should be just `openlayers`

This issue is related to rollup.js, here is the url that  is related to this problem:
[https://github.com/angular/angular/issues/16084](https://github.com/angular/angular/issues/16084)

To fix this issue: I need access to  "annotateForClosureCompiler" property so it can be set to false. At this moment it's part of `tsconfig.ngc.json` and it set to `true` by default. Would it be possible to extend packagr so that I can fiddle with tsconfig properties via `ng-package.json` file?

Thanks Alex

**Comment by dherges** [comment] 2017-09-06 06:27
Do you mean #101 ?

**Comment by dherges** [comment] 2017-09-06 06:38
On your specific question: No. The purpose of `ng-packagr` is to take away the burden of configuring a bunch of tools - at least as much as possible. It is a very opionated tool that compiles TypeScript source files to Angular Package Format. Should the recommendation / best-practice for closure compiler change (or maybe a new version of Angular Package Format is introduced), the internal default configurations will be changed.

Thanks for the hint at the related Angular Issue! :+1:

**Comment by adjioev** [comment] 2017-09-07 05:21
Thanks David,

so is there a solution that I can apply at this moment? From what I understood there are three solutions at this moment - remove types from package.js, set annotateForClosureCompiler property to false or set target to es5.

**Comment by dherges** [comment] 2017-09-07 05:46
Workaround is:

```json
{
    "$schema": "../../node_modules/ng-packagr/lib/ng-package.schema.json",
    "lib": {
        "externals": {
            "@ngx-translate/core": "ngx-translate-core",
            "@ngx-translate/core/index": "ngx-translate-core"
        }
    }
}
```

**Comment by adjioev** [comment] 2017-09-07 06:11
This is my current `ng-package.json`
```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "@ngrx/store": "@ngrx/store",
      "openlayers": "openlayers",
      "openlayers/index": "openlayers"
    }
  }
}
```
but packagr still producess the following line 
`import { Map, View, control, format, layer, proj, source } from 'openlayers/index';`

**Comment by gotnull** [comment] 2017-09-08 01:01
I'm also running into the same problem as @adjioev

`import { Map, View, control, format, layer, proj, source } from 'openlayers/index';`

**Comment by dherges** [comment] 2017-09-08 18:13
Yes, it still produces those `openlayers/index` imports but should resolve them properly when bundling the lib to fesm and umd. At least with `ngx-translate` it is working.

**Comment by dherges** [comment] 2017-09-21 08:29
I would like to track the cause for the error in #101 and close this issue therefore.

Please give an update if the workaround still produces an error for you and re-open.

**Closed by dherges** 2017-09-21 08:29 UTC
Labels: documentation
