### ISSUE TITLE
BUILD ERROR - When adding clarity package

### ISSUE THREAD

**Issue by keshav1007** [dherges/ng-packagr#947] opened 2018-06-14 07:11 UTC
## Type of Issue
[ ] Bug Report
```

## Description

Unable to complete the build when adding clarity as a package in the application package. 

I have tried adding clarity to externals in ng-package.json but still build fails.


#### How To Reproduce

Please use this repo - https://github.com/keshav1007/ng-packagr

 - Do yarn install
 - Do yarn packagr

Error : 

![image](https://user-images.githubusercontent.com/20353796/41396828-c1f08706-6fcf-11e8-9188-acdadc6af0fb.png)

BUILD ERROR
(1,1): : Directive ɵcb, Property 'block' does not exist on type 'ClrDatagridColumnToggleButton'.
node_modules/@clr/angular/clr-angular.d.ts.ClrHeader.html(6,13): : Property 'NAV_LEVEL_1' does not exist on type 'ResponsiveNavCodes'.
node_modules/@clr/angular/clr-angular.d.ts.ClrHeader.html(14,13): : Property 'NAV_LEVEL_2' does not exist on type 'ResponsiveNavCodes'.

Error: (1,1): : Directive ɵcb, Property 'block' does not exist on type 'ClrDatagridColumnToggleButton'.
node_modules/@clr/angular/clr-angular.d.ts.ClrHeader.html(6,13): : Property 'NAV_LEVEL_1' does not exist on type 'ResponsiveNavCodes'.
node_modules/@clr/angular/clr-angular.d.ts.ClrHeader.html(14,13): : Property 'NAV_LEVEL_2' does not exist on type 'ResponsiveNavCodes'.

    at Object.<anonymous> (/Users/keshavs/test/test-ngPackagr/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at next (native)
    at /Users/keshavs/test/test-ngPackagr/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at __awaiter (/Users/keshavs/test/test-ngPackagr/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/keshavs/test/test-ngPackagr/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/Users/keshavs/test/test-ngPackagr/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:26:32)
    at next (native)
    at /Users/keshavs/test/test-ngPackagr/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at __awaiter (/Users/keshavs/test/test-ngPackagr/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:3:12)
    at exports.compileNgcTransform.transform_1.transformFromPromise (/Users/keshavs/test/test-ngPackagr/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:17:75)

error An unexpected error occurred: "Command failed.



#### Expected Behaviour

Build should success.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.2
@angular/*: 5.0.0
typescript: 2.4.2
rxjs: 5.5.2
node: 6.11.3
npm/yarn: 1.5.1
```

**Comment by alan-agius4** [comment] 2018-06-14 12:31
From the error, it seems that this is not a bug from `ng-packagr` but rather from the `clarity` library which has templates errors. Please log an issue when them.

We use [fullTemplateTypeCheck](https://angular.io/guide/aot-compiler#fulltemplatetypecheck) when building and thus, any template errors will be reported.

**Comment by keshav1007** [comment] 2018-06-18 11:17
figured out the issue after a long day.. the package/folder structure was not proper. I took ng-packaged as reference and made the project folder structure and i am able to build the library separately now.

But when i import the built library i am getting the following error for more components:

Cannot determine the module for class XXXComponent in /Users/keshavs/orgCD/xxx/lib/app/modules/cost-drivers/components/xxx/xxx.component.ts! Add XXXComponent to the NgModule to fix it.

I am getting the above error for more components

**Comment by keshav1007** [comment] 2018-06-18 11:33
Yes I am registering my components inside the declarations and exports in the ngModule.

I have exported all components in this module so I am just consuming this module in my application something like

Import xxxModule from 'my-lib';

**Comment by alan-agius4** [comment] 2018-06-18 11:35
And how are you consuming the library?

**Comment by keshav1007** [comment] 2018-06-18 11:38
Import xxxModule from 'my-lib'

I am consuming the library like this

**Comment by alan-agius4** [comment] 2018-06-18 11:40
What I meant, was are you using `tsconfig paths` that points to the dist? are you using `npm link`, `npm pack` etc..

Can you share a reproduction?

**Comment by keshav1007** [comment] 2018-06-18 11:42
No.. I am not using any of these.. I am not aware of it.. generally for other packages we don't mention paths or anything right? We just install the npm package and use it.

**Comment by alan-agius4** [comment] 2018-06-18 11:43
Ah okay, so you releasing it, and afterwards you are getting it the error. Not with a sort of integration test.

**Comment by keshav1007** [comment] 2018-06-18 11:44
yes.. i have already published the built dist folder as an npm package and i am using the same

**Comment by alan-agius4** [comment] 2018-06-18 11:46
If it's in the public npm registry can you share the package name and
version so I can have a quick look at it?

**Comment by keshav1007** [comment] 2018-06-18 11:48
https://www.npmjs.com/package/cost-drivers -  it is available here :)

**Comment by alan-agius4** [comment] 2018-06-18 12:00
What I am seeing is that in https://unpkg.com/cost-drivers@0.0.2/esm2015/app/common/modules.js `PopupComponent` has been registered under `imports` and not `declerations`.

**Comment by keshav1007** [comment] 2018-06-18 12:29
yes PopupComponent is just named as component but it is a module :P so i have not mentioned it under declarations.. but the issue seems to be on other components right? as per the build error messages - 

ERROR in : Cannot determine the module for class AdditionalCostComponent in /Users/keshavs/orgCD/cost-drivers/lib/app/modules/cost-drivers/components/additional-cost/additional-cost.component.ts! Add AdditionalCostComponent to the NgModule to fix it.
Cannot determine the module for class FacilitiesComponent in /Users/keshavs/orgCD/cost-drivers/lib/app/modules/cost-drivers/components/facilities/facilities.component.ts! Add FacilitiesComponent to the NgModule to fix it.
Cannot determine the module for class CostDriversComponent in /Users/keshavs/orgCD/cost-drivers/lib/app/modules/cost-drivers/components/cost-drivers.component.ts! Add CostDriversComponent to the NgModule to fix it.
Cannot determine the module for class LaborComponent in /Users/keshavs/orgCD/cost-drivers/lib/app/modules/cost-drivers/components/labor/labor.component.ts! Add LaborComponent to the NgModule to fix it.
Cannot determine the module for class LicensingComponent in /Users/keshavs/orgCD/cost-drivers/lib/app/modules/cost-drivers/components/licensing/licensing.component.ts! Add LicensingComponent to the NgModule to fix it.
Cannot determine the module for class MaintenanceComponent in /Users/keshavs/orgCD/cost-drivers/lib/app/modules/cost-drivers/components/maintenance/maintenance.component.ts! Add MaintenanceComponent to the NgModule to fix it.
Cannot determine the module for class NetworkComponent in /Users/keshavs/orgCD/cost-drivers/lib/app/modules/cost-drivers/components/network/network.component.ts! Add NetworkComponent to the NgModule to fix it.
Cannot determine the module for class ServerHardwareComponent in /Users/keshavs/orgCD/cost-drivers/lib/app/modules/cost-drivers/components/server-hardware/server-hardware.component.ts! Add ServerHardwareComponent to the NgModule to fix it.
Cannot determine the module for class StorageComponent in /Users/keshavs/orgCD/cost-drivers/lib/app/modules/cost-drivers/components/storage/storage.component.ts! Add StorageComponent to the NgModule to fix it.

I have tried adding "lib" folder inside the exclude property in tsconfig also. but no luck

**Comment by alan-agius4** [comment] 2018-06-18 12:41
Any particular reason why you are using CUSTOM_ELEMENTS_SCHEMA? If you are not using web components ta best to remove it so that you have more build errors during building the library

**Comment by keshav1007** [comment] 2018-06-18 15:33
Ok.. after excluding lib in tsconfig.json my build is running properly but with one error - ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'lib' in '/Users/keshavs/orgCD/cost-drivers/src/app'

But i haven't referenced the lib anywhere in this application :(

**Comment by keshav1007** [comment] 2018-06-18 15:47
ng server is working properly

ng build --prod is failing with the mentioned error

**Comment by alan-agius4** [comment] 2018-06-18 16:00
That looks like an issue with barrel files. By any chance are you using
barrel files?

**Comment by alan-agius4** [comment] 2018-06-18 16:03
The lib file is generated by Angular Compiler. Are you using barrel files by any chance? As that might be an issue.

**Comment by keshav1007** [comment] 2018-06-18 16:07
No i am not using any barrel files to import from a single file

**Comment by keshav1007** [comment] 2018-06-18 16:18
I assume whatever worked for you also will fail if ng build --prod is executed for your project

**Comment by alan-agius4** [comment] 2018-06-18 16:27
After having a look at this, it looks like in the metadata you are the library is exported as `lib` however you are naming it as `cost-drivers`, if you take a look at `lib.metadata.json`

Most likely your `package.json` `name` property is is set to `lib`

**Comment by keshav1007** [comment] 2018-06-18 16:49
After changing the name properly i am getting other errors :(

ERROR in src/app/app.routing.ts(23,10): error TS2305: Module '"/Users/keshavs/work/vrbc-ui/node_modules/cost-drivers/cost-drivers"' has no exported member 'AdditionalCostComponent'.
src/app/app.routing.ts(24,10): error TS2305: Module '"/Users/keshavs/work/vrbc-ui/node_modules/cost-drivers/cost-drivers"' has no exported member 'FacilitiesComponent'.
src/app/app.routing.ts(25,10): error TS2305: Module '"/Users/keshavs/work/vrbc-ui/node_modules/cost-drivers/cost-drivers"' has no exported member 'CostDriversComponent'.
src/app/app.routing.ts(26,10): error TS2305: Module '"/Users/keshavs/work/vrbc-ui/node_modules/cost-drivers/cost-drivers"' has no exported member 'LaborComponent'.
src/app/app.routing.ts(27,10): error TS2305: Module '"/Users/keshavs/work/vrbc-ui/node_modules/cost-drivers/cost-drivers"' has no exported member 'LicensingComponent'.
src/app/app.routing.ts(28,10): error TS2305: Module '"/Users/keshavs/work/vrbc-ui/node_modules/cost-drivers/cost-drivers"' has no exported member 'MaintenanceComponent'.
src/app/app.routing.ts(29,10): error TS2305: Module '"/Users/keshavs/work/vrbc-ui/node_modules/cost-drivers/cost-drivers"' has no exported member 'NetworkComponent'.
src/app/app.routing.ts(30,10): error TS2305: Module '"/Users/keshavs/work/vrbc-ui/node_modules/cost-drivers/cost-drivers"' has no exported member 'ServerHardwareComponent'.
src/app/app.routing.ts(31,10): error TS2305: Module '"/Users/keshavs/work/vrbc-ui/node_modules/cost-drivers/cost-drivers"' has no exported member 'StorageComponent'.

But i have exported all these components from module.. you can take the latest npm version 
cost-drivers : 0.0.3

**Comment by alan-agius4** [comment] 2018-06-18 16:55
Doesn’t look like it.

https://unpkg.com/cost-drivers@0.0.3/public_api.d.ts

**Comment by keshav1007** [comment] 2018-06-18 17:17
A BIG BIG BIG thanks to you.. my bad i exported only in the module and not in the public_api.. it works fine now.. AOT build is also working properly.. thanks a lot 👍

**Comment by alan-agius4** [comment] 2018-06-18 17:27
Awesome, please close the issue in that case :)

**Closed** 2018-06-18 17:30 UTC
