### ISSUE TITLE
error TS6053: File 'xxxxxxx/public_api.ts' not found.

### ISSUE THREAD

**Issue by Alsmile** [dherges/ng-packagr#375] opened 2017-12-07 09:23 UTC
[2.0.0-rc.5 ] error TS6053: File 'xxxxxxxx/public_api.ts' not found.
```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "src": "src/lib",
  "dest": "dist",
  "lib": {
    "entryFile": "public_api.ts"
  }
}
```
github url: [https://github.com/le5le-com/le5le-components/tree/ng5](https://github.com/le5le-com/le5le-components/tree/ng5)

**Comment by dherges** [comment] 2017-12-07 18:17
Regression or breaking change?

The #361 refactoring changed the behaviour of the `src` attribute. The file path of `lib.entryFile` is now being resolved relative to the `ng-package.json`/ `package.json` file.

Historically the `src` attribute was needed for copying source files (resource inlining, tsc) on disk. Since #356, ts files are no longer copied on disk. Has the `src` property become abandoned? Is it used anymore?

Workaround for you is to change `lib.entryFile: "src/lib/public_api.ts"`

**Comment by Alsmile** [comment] 2017-12-08 03:30
Change lib.entryFile: "src/lib/public_api.ts" will get error on build css.

**Comment by Ks89** [comment] 2017-12-11 19:50
> Change lib.entryFile: "src/lib/public_api.ts" will get error on build css.

I have the same problem.

```
BUILD ERROR
Cannot inline stylesheet [object Object]
Error: Cannot inline stylesheet [object Object]
    at Object.<anonymous> (/Users/ks89/git/PROJECT/node_modules/ng-packagr/lib/steps/assets.js:80:31)
    at Generator.throw (<anonymous>)
    at rejected (/Users/ks89/git/PROJECT/node_modules/ng-packagr/lib/steps/assets.js:5:65)
    at <anonymous>
```

**Comment by dherges** [comment] 2017-12-16 08:45
Hi all,

you encountered a breaking change that wasn't mentioned in the rc6 changelog. The rc7 changelog should clarify it and the `src` property is eventually going to be dropped in 2.0

#411, #416, #415

**Comment by dherges** [comment] 2017-12-29 08:37
Fixed / addressed in rc8

**Closed by dherges** 2017-12-29 08:37 UTC
Labels: radar +
