### ISSUE TITLE
[lib.externals] support importing the rxjs operators directly

### ISSUE THREAD

**Issue by aitboudad** [dherges/ng-packagr#56] opened 2017-06-23 11:57 UTC
rxjs operators can be used by importing the operators directly instead the patch operators

```ts
import {map} from 'rxjs/operator/map';
map.call(exObservable, ...).subscribe(...);
```

Right now I get the following error:
```console
BUILD ERROR
'map' is not exported by node_modules/rxjs/operator/map.js
Error: 'map' is not exported by node_modules/rxjs/operator/map.js
```

**Comment by dherges** [comment] 2017-06-24 19:44
dupe of #49 

fixed by #57

**Closed** 2017-06-24 19:44 UTC
