### ISSUE TITLE
Include .js libraries and image assets

### ISSUE THREAD

**Issue by pagner** [dherges/ng-packagr#445] opened 2017-12-26 07:11 UTC
Sorry if this has already been answered but I have been searching for a way to include images and script files from my assets folder. I would think this would be easy. thanks

./assets/js/script.js
./assets/img/myImage.png

**Comment by dherges** [comment] 2018-01-06 16:55
Yes, duplicate of #123

**Closed by dherges** 2018-01-06 16:55 UTC
