### ISSUE TITLE
package.json for packaged library changed (2.0.0-rc.4 vs 2.0.0-rc-6)

### ISSUE THREAD

**Issue by JulienOuvrard** [dherges/ng-packagr#416] opened 2017-12-15 14:48 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

package.json file in packaged library is not the same after upgrading version of ng-packagr (2.0.0-rc.4 vs 2.0.0-rc.6)

#### How To Reproduce
Here is the project tree : 
```
- my-project
|__+ src
|__- my-lib
|   |__+ src
|   |__ package.json
|   |__ public_api.ts
|__+target
|__+tools
|__ package.json
|__ ng-package.json
```

With rc-4, package.json in the packaged library was my-lib package.json but in rc-6 it's my-project package.json

FYI
ng-package.json
```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "src": "my-lib",
  "dest": "target/my-lib",
  "lib": {
    "entryFile": "my-lib/public_api.ts"
  }
}
```

my-project package.json scripts
```
{
...
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "packagr": "ng-packagr -p ng-package.json && npm run copy",
    "copy": "node ./tools/copy-assets.js"
  },
  "private": true,
...
}
```
my-lib package
```
{
  "name": "my-lib",
  "version": "1.0.0",
  "description": "",
  "author": "My society",
  "license": "MIT",
  "peerDependencies": {
...
   }
}
```

Maybe i didn't understood well the new documentation and need more explanations !

#### Expected Behaviour

Same behaviour of rc-4 for rc-6. Or documentation for this change

#### Version Information

```
ng-packagr: 2.0.0-rc.6
@angular/*: 5.1.1
typescript: 2.5.3
node: 7.10.0
npm: 4.2.0
```

**Comment by JulienOuvrard** [comment] 2017-12-15 16:36
In fact generated files are weirdly named compared to their content:
```
-target
|__-my-lib
|  |__+bundles
|  |__+esm2015
|  |__+esm5
|  |__+src
|  |__ my-project.d.ts
|  |__ my-project.metadata.js
|  |__ package.json
|  |__ public_api.ts
```

- In src folder i found only definition of my-lib components
- Files names in bundles, esm2015 and esm5 folders starts with my-project but their content are only related to my-lib components
- package.json, as mentioned in the first message, is my-project package.json

I really don't understand what i have missed in documentation between rc-4 and rc-6

**Comment by dherges** [comment] 2017-12-15 21:25
Hi @JulienOuvrard,

yes, the reason for `src` has been that ng-packagr used to regex/copy files for resource inlining. In the 2.x version, it's going to replace that with the typescript transformations API and thus there is no more need for globbing file patterns like `<src>/**/*.ts`.

The `src` property is eventually going to be dropped.

**Comment by dherges** [comment] 2017-12-16 07:47
What I was going to say: in your folder structure, you should move the `ng-package.json` to the `my-lib` folder, right next to the `package.json` of the library.

**Comment by dherges** [comment] 2017-12-16 07:47
Duplicate of #411

**Comment by JulienOuvrard** [comment] 2017-12-18 09:07
Hi @dherges ,
thanks for the quick reply, the suggestion effectively solved my initial problem

**Closed** 2017-12-29 08:55 UTC
Labels: question
