### ISSUE TITLE
[Help] Build Angular library with external dependencies

### ISSUE THREAD

**Issue by ahnpnl** [dherges/ng-packagr#979] opened 2018-06-26 13:29 UTC
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Request for help
```

## Description
Hi, I know this question might be already answered before but I did try all the solutions and it doesn't work for my case. I want to build a library using `Angular CLI` 6 (with `ng-packagr` included) and my external dependencies is `ids-enterprise-ng`. I keep getting the error during the `ngc` phase. I hope someone can help me.

#### How To Reproduce
Here is the repo I use to create the library: https://github.com/ahnpnl/ng-packagr-enterprise-ng
- Install dependencies by running `yarn`
- Build the library by running `ng build test-lib --prod`
- Observe in the console with bunch of errors.

#### Expected Behaviour
I hope someone can help me to find a way to use this external dependency to build the library.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            3.0.3
@angular/compiler:     6.0.6
rollup:                0.59.4
tsickle:               0.30.0
typescript:            2.7.2
rxjs: 6.0.0
node: 8.11.2
yarn: 1.7.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_
```
ids-enterprise-ng: 4.7.0
```

**Comment by alan-agius4** [comment] 2018-06-26 14:36
Thanks for the repo.

I will try to look into it later on today or tomorrow.

Can you please provide an extract of the error that you are experiencing maybe it will be faster to solve? Also it will be an aid for other people facing the same issue.

**Comment by alan-agius4** [comment] 2018-06-26 16:58
For the record the error is as follows;

```
Error: projects/test-lib/src/lib/test-lib.module.ts(7,5): error TS2304: Cannot find name 'SohoComponentsModule'.
```

The problem is that in the mentioned file is the `SohoComponentsModule` is never imported.

<img width="626" alt="screen shot 2018-06-26 at 18 57 56" src="https://user-images.githubusercontent.com/17563226/41927578-e5ca7e28-7972-11e8-9bf4-c9f92af400ab.png">

**Comment by ahnpnl** [comment] 2018-06-26 17:01
Hi, thank you for their response. Indeed that was a typo I made but however, if I import it and I still couldn't build the lib. I did contact the team who is responsible for that repo and they suggested me to wait for their next version. I did try with their beta next version and I could build my lib again. I think we can close this one since they won't fix with current release but the next release 😃

**Comment by alan-agius4** [comment] 2018-06-26 17:04
In that case please close the issue.

Thanks

**Closed** 2018-06-26 17:04 UTC
