### ISSUE TITLE
[Bug] Components: multiple styleUrls processed incorrectly

### ISSUE THREAD

**Issue by denver-HJS** [dherges/ng-packagr#424] opened 2017-12-19 00:24 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

**Windows**: When trying to bundle a component that contains multiple values in the `styleUrls` property the assets processing step fails. (See below for more details)

**Unix/Linux**: My colleague was able to run the process, but all styles were concatenated into a single string value. This caused it's own issue where some styles were applied but not others. I think this may be because the `<style>` tag has a max char limit (although I couldn't verify that). When separating the *one* string into *three* all styles were applied correctly.

#### How To Reproduce

Include multiple style URLs in the component definition. Ensure the total number of lines is greater than 611 (that's the total number combined from the component's style definitions) or at least a reasonable/realistic content length for a highly styled component.

 

#### Expected Behaviour

The expected behavior is that the three style URL references become translated to inline styles each with their own dedicated place in the array. (3 style URLs : 3 inline strings)

#### Error Output

Component Decorator:

```
@Component({
  selector: 'web-wrapper-header',
  templateUrl: './web-wrapper-header.component.html',
  styleUrls: [
    './web-wrapper-header-animations.component.scss',
    './web-wrapper-header-toolbar.component.scss',
    './web-wrapper-header-sidenav.component.scss'
  ],
  providers: [
    WebWrapperUtilsService
  ],
  encapsulation: ViewEncapsulation.None
})
export class WebWrapperHeaderComponent implements OnInit, OnDestroy {
```

*Output*:
> ng-packagr -p ng-package.json
> 
> Building Angular Package
> Building from sources for entry point 'web-wrapper'
> Cleaning build directory
> Extracting templateUrl and styleUrls
> Processing assets
> 
> BUILD ERROR
> Cannot inline stylesheet C:\src\git\web-wrapper\src\app\components\web-wrapper-header\,
> Error: Cannot inline stylesheet C:\src\git\web-wrapper\src\app\components\web-wrapper-header\,
>     at Object.<anonymous> (C:\src\git\xpo-web-wrapper\node_modules\ng-packagr\lib\steps\assets.js:87:31)
>     at Generator.throw (<anonymous>)
>     at rejected (C:\src\git\web-wrapper\node_modules\ng-packagr\lib\steps\assets.js:5:65)
>     at <anonymous>
> 
> Build failed. The working directory was not pruned. Files are stored at {ngPackage.workingDirectory}.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 111
> npm ERR! web-wrapper@2.2.2 build-npm: `ng-packagr -p ng-package.json`
> npm ERR! Exit status 111
> npm ERR! 
> npm ERR! Failed at the web-wrapper@2.2.2 build-npm script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

#### Version Information

```
Angular CLI: 1.6.1
Node: 8.9.3
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.0.1
@angular/cli: 1.6.1
@angular/compiler-cli: 5.0.2
@angular/flex-layout: 2.0.0-beta.12
@angular/language-service: 5.0.2
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
ng-packagr@2.0.0-rc.7
tsickle@0.25.5

```
**OS Version:** Windows 7 SP1 x64 | Build x64.2015.4.0

**Comment by dherges** [comment] 2017-12-19 19:10
Hi @denver-HJS,

thanks for reporting. I guess it's a duplicate of #407 

A PR for the issue is welcome!

**Closed by dherges** 2017-12-19 19:11 UTC
Labels: duplicate

**Comment by denver-HJS** [comment] 2017-12-28 23:20
@dherges can you make the `log.debug` statements show up when running the ng-packagr command? I think these will be helpful in my dev environment, but I can't find anything in the guides.

**Comment by dherges** [comment] 2017-12-29 08:29
Setting a `DEBUG` environment variable will print out debug logs, e.g. `DEBUG=true ng-packagr -p<...>`

**Comment by dherges** [comment] 2017-12-30 08:28
Fix in rc.9
